### ISSUE TITLE
Using ufw-blocklist with other ufw rules

### ISSUE THREAD

**Issue by BillTheGoat** [poddmo/ufw-blocklist#3]
Looking over your code and installation process, it appears that you just take over ufw. I have existing rules to limit ports etc that I would like to keep. Is there a way to set this up so that my original rules still work, but ufw-blocklist is simply appended?

Sorry if this question is too naive, I just started using ufw.

**Comment by poddmo** [comment]
It is fair to say that ufw-blocklist overrides ufw by using insert rules. That is intentional as the intent is to block all traffic to and from hosts on the blocklist with extreme prejudice. I also have allow and allow limit rules for ports but I don't want any of them available to hosts on the blocklist.
Your original rules should still work, unless they are to or from hosts on the blocklist. Please let me know if you don't get that result.
